export const GRAPHICAL = "GRAPHICAL"
export const ARTIFICAL = "ARTIFICAL_BASIS"
export const SIMPLEX = "SIMPLEX"
export const TYPE_FUNCTION = "TYPE_FUNCTION"
export const TYPE_REFERENCE = "TYPE_REFERENCE"
export const TYPE_BASIS = "TYPE_BASIS"

export const CHANGE_VAR_COUNT = "CHANGE_VAR_COUNT"
export const CHANGE_REF_COUNT = "CHANGE_REF_COUNT"
export const CHANGE_TYPE_DATA = "CHANGE_TYPE_DATA"
export const CHANGE_GENERAL_MESSAGE = "CHANGE_GENERAL_MESSAGE"

